package org.firstinspires.ftc.teamcode.common;

public enum AutoStates {
    preloads,
    wait_for_preload_shot,
    intake1,
    shoot1,
    wait_for_shot1,
    gate1,
    swerve,
    wait_at_gate1,
    shoot2,
    wait_for_shot2,
    gate2,
    wait_at_gate2,
    shoot3,
    wait_for_shot3,
    intake2,
    shoot4,
    square4,
    wait_for_shot4,
    teleop_standby,
    wait1,
    wait_at_path1,
    wait2,
    wait_at_path2,
    square1,
    square1_intake,
    square2,
    wait3,
    wait_at_path3,
    square3,
    end
}
